/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.btc;


import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import java.util.Arrays;


@SpringBootApplication
@Slf4j
public class App {
   // @Autowired
   // HazelManager hazelManager;
    public static void main(String[] args) {

     ApplicationContext applicationContext = SpringApplication.run(App.class, args);
        log.info(" was started.");
 // TODO was added for performance testing
       /* String[]beans = applicationContext.getBeanDefinitionNames();
        Arrays.sort(beans);
        for (String bean : beans) {
            System.out.println(bean);
        }*/
       // hazelManager.start();
    }


}
